### ISSUE TITLE
A country is missing

### ISSUE THREAD

**Issue by dmythro** [matiassingers/emoji-flags#2]
Hi, just noticed your data misses Kosovo.

By the tip, added Emoji to our [Countries](https://github.com/annexare/Countries) data library build, but see that this country is missing. Could you please check it out?

**Comment by dmythro** [comment]
Not using this library as dependency anymore, because it's easy to [just generate emoji data for flags by ISO 3166-1 alpha-2 code](https://github.com/annexare/Countries/pull/11).

But suggesting to update this data anyways. Cheers.

**Comment by reustle** [comment]
Belgium is also missing

**Comment by dmythro** [comment]
@reustle yeah, that's why it's better to just generate like mentioned above :)

**Comment by matiassingers** [comment]
Kosovo has been added to the data set, closing this issue.

@reustle Belgium is in the data set.
