### ISSUE TITLE
How to display on Windows 10?

### ISSUE THREAD

**Issue by dfdumaresq** [matiassingers/emoji-flags#6]
The emoji-flags do not appear on either Chrome or Edge in Windows 10. They work fine Chrome in Mac.

Below is a screen grab from Chrome on Windows 10. I'm just displaying the single flag row in a tag and below that is HTML.

          <pre>{JSON.stringify({code: 'AR', emoji: '🇦🇷', unicode: 'U+1F1E6 U+1F1F7', name: 'Argentina', title: 'flag for Argentina'}, null, 2)}</pre>
          <p>I will display &#129409;</p>
          <p>I will display &#x1F981;</p>

![image](https://user-images.githubusercontent.com/20051/80045070-43d4ed00-84bb-11ea-871b-e6ca842b44d7.png)

From my testing, the emoji value will not display, but the HTML equivalent will. Is there a configuration value that I might use for this?

**Comment by dfdumaresq** [comment]
I can see this is an issue with Windows 10 not being updated to display emoji flags. Do you have any plans to provide an alternative HTML setting?
https://emojipedia.org/flags/

**Comment by matiassingers** [comment]
I'm afraid this package is just for Unicode emoji flags, and it's outside the scope of this project to add Windows support.

**Comment by woutdp** [comment]
If anyone is hitting against this issue, just wanted to mention this fixed it for me: https://github.com/talkjs/country-flag-emoji-polyfill
