### ISSUE TITLE
Emoji Flags are not visible in chrome windows is just displaying country code

### ISSUE THREAD

**Issue by Rubi91** [matiassingers/emoji-flags#9]

**Comment by etorhub** [comment]
Hello @Rubi91,

This issue was already discussed in https://github.com/matiassingers/emoji-flags/issues/6

I was also expecting it to work, but I suggest you a workaround, like using a library that has its own SVGs.

Regards,

**Comment by matiassingers** [comment]
I believe this is a current limitation on Windows as a platform, see https://blog.getemoji.com/post/620280709025841152/how-to-use-flag-emojis-on-windows
